name: CI/CD DevOps Avançado

on:
  push:
    branches: [ master ]

jobs:
  build_e_teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # ... suas etapas de build da imagem ...

      - name: Create KinD cluster
        uses: engineerd/setup-kind@v0.6.2
        with:
          version: v0.24.0
          wait: 300s

      - name: Check cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to KinD
        run: |
          kubectl apply -f 06-DevopsAvancado/k8s-deployment.yaml

