name: CI/CD DevOps Avançado

on:
  push:
    branches: [ master ]

jobs:
  build_e_teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Definir tag da imagem
        id: set_tag
        run: echo "::set-output name=image_tag::my-image-$(date +%s)"
      
      - name: Build da imagem Docker
        id: build_image
        run: |
          IMAGE_TAG=${{ steps.set_tag.outputs.image_tag }}
          echo "Usando a tag: $IMAGE_TAG"
          docker build ./06-DevopsAvancado --file ./06-DevopsAvancado/Dockerfile --tag $IMAGE_TAG
      

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}   # conteúdo do kubeconfig como secret
        run: |
          echo "$KUBECONFIG_B64" | base64 -d > kubeconfig
      
          export KUBECONFIG="${PWD}/kubeconfig"
      
          kubectl apply -f k8s-deployment.yaml
