name: Build e teste da imagem Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_e_teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Definir tag da imagem
        id: set_tag
        run: echo "::set-output name=image_tag::my-image-$(date +%s)"
      
      - name: Build da imagem Docker
        id: build_image
        run: |
          IMAGE_TAG=${{ steps.set_tag.outputs.image_tag }}
          echo "Usando a tag: $IMAGE_TAG"
          docker build ./03-DevopsBasico --file ./03-DevopsBasico/Dockerfile --tag $IMAGE_TAG
      
      - name: Teste da imagem Docker
        run: |
          IMAGE_TAG=${{ steps.set_tag.outputs.image_tag }}
          echo "Testando a imagem com a tag: $IMAGE_TAG"
          docker run -d --name my-container -p 3000:3000 $IMAGE_TAG
          sleep 5
          docker logs my-container
          docker stop my-container
